# Generated by Django 4.2.4 on 2023-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_package_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='images_2',
            field=models.ImageField(blank=True, null=True, upload_to='turs/'),
        ),
    ]
